In [1]:
ls

1.go2page.ipynb                 ipage_down.py         mouse2human/  test/
1.msigdb2page.ipynb             ipage_draw_matrix.sh  msigdb_v7.4/
2.human2mouse-gene-names.ipynb  ipage_loop.sh         __pycache__/
annotations/                    LICENSE               scripts/

In [2]:
import pandas as pd

In [44]:
HOM_df = pd.read_csv('mouse2human/HOM_MouseHumanSequence.rpt',sep='\t')
# [[
#     'Common Organism Name','Symbol'
# ]]

In [45]:
HOM_df

,DB Class Key,Common Organism Name,NCBI Taxon ID,Symbol,EntrezGene ID,Mouse MGI ID,HGNC ID,OMIM Gene ID,Genetic Location,"Genomic Coordinates (mouse: , human: )",Nucleotide RefSeq IDs,Protein RefSeq IDs,SWISS_PROT IDs
0,41237484,"mouse, laboratory",10090,N4bp2l2,381695,MGI:2687207,NaN,NaN,Chr5 89.57 cM,Chr5:150531472-150589648(-),"XM_036165251,XM_030254630,XM_036165249,XM_0361...","XP_036021142,XP_036021141,XP_036021144,XP_0301...",Q8JZS6
1,41237484,human,9606,N4BP2L2,10443,NaN,HGNC:26916,OMIM:615788,Chr13 q13.1,Chr13:32432488-32542710(-),"NM_001387223,NM_001387225,NM_001395224,NM_0148...","NP_001374008,NP_001265361,NP_001307765,NP_0013...",Q92802
2,41237485,"mouse, laboratory",10090,Tomm6,66119,MGI:1913369,NaN,NaN,Chr17 23.87 cM,Chr17:47997571-47999311(-),"NM_025365,NM_001164729","NP_079641,NP_001158201",Q9CQN3
3,41237485,human,9606,TOMM6,100188893,NaN,HGNC:34528,OMIM:616168,Chr6 p21.1,Chr6:41787443-41789896(+),"NM_001382294,NM_001134493","NP_001127965,NP_001369223",Q96B49
4,41237486,"mouse, laboratory",10090,Stac,20840,MGI:1201400,NaN,NaN,Chr9 61.81 cM,Chr9:111390505-111519416(-),"NM_016853,NM_001324546,XM_006512016","XP_006512079,NP_001311475,NP_058549",P97306
...,...,...,...,...,...,...,...,...,...,...,...,...,...
46436,41259309,"mouse, laboratory",10090,Zfp955b,100043468,MGI:4834573,NaN,NaN,Chr17 17.98 cM,Chr17:33508518-33526215(+),"XM_030249401,NM_001142957,XM_030249402","NP_001136429,XP_030105261,XP_030105262",NaN
46437,41259310,"mouse, laboratory",10090,Zfp955a,77652,MGI:4834570,NaN,NaN,Chr17 17.98 cM,Chr17:33458692-33474119(-),"XM_006525122,NM_029952","XP_006525185,NP_084228",NaN
46438,41259311,"mouse, laboratory",10090,Zfp956,101197,MGI:2141515,NaN,NaN,Chr6 22.94 cM,Chr6:47930324-47942234(+),NM_178898,NP_849229,NaN
46439,41259312,"mouse, laboratory",10090,Zfp964,636741,MGI:3646490,NaN,NaN,Chr8 33.88 cM,Chr8:70107129-70119632(+),"XM_011242316,NM_001177527","XP_011240618,NP_001170998",NaN
46440,41259313,"mouse, laboratory",10090,Zim1,22776,MGI:1341879,NaN,NaN,Chr7 3.87 cM,Chr7:6677443-6699521(-),"XM_011250495,XM_011250498,XM_011250497,NM_0117...","XP_011248800,NP_035899,XP_011248799,XP_0112487...",NaN

In [41]:
temp = []

for i in range(0,HOM_df.shape[0]-1,2):
    if HOM_df['Common Organism Name'].tolist()[i] != 'mouse, laboratory':
        temp.append(i)
    if HOM_df['Common Organism Name'].tolist()[i + 1] != 'human': 
        temp.append(i+1)

      Common Organism Name    Symbol
19       mouse, laboratory     Lypd8
20                   human     LYPD8
21       mouse, laboratory    Lypd8l
34                   human  HLA-DRB3
36                   human  HLA-DRB5
...                    ...       ...
46431    mouse, laboratory    Zfp868
46433    mouse, laboratory    Zfp945
46435    mouse, laboratory    Zfp954
46437    mouse, laboratory   Zfp955a
46439    mouse, laboratory    Zfp964

[24759 rows x 2 columns]